kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gatekeeper-ops-role
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - config.gatekeeper.sh
    resources:
      - configs
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - config.gatekeeper.sh
    resources:
      - configs/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - constraints.gatekeeper.sh
    resources:
      - '*'
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - templates.gatekeeper.sh
    resources:
      - constrainttemplates
  - verbs:
      - get
      - list
    apiGroups:
      - operator.gatekeeper.sh
    resources:
      - gatekeepers
  - verbs:
      - get
      - list
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations 


