apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "openshift-gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: ""
        version: "v1"
        kind: "ResourceQuota"        
  match:
    - excludedNamespaces: ["gatekeeper-project-excluded"]
      processes: ["*"]
  validation:
    traces:
      - user: "cromerob"
        kind:
          group: "*"
          version: "v1"
          kind: "Deployment"
          dump: "All"      
