apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "openshift-gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: ""
        version: "v1"
        kind: "Pod"
      - group: "*"
        version: "v1"
        kind: "Deployment"
      - group: "*"
        version: "v1"
        kind: "ReplicaSet"  
    match:
      - excludedNamespaces: ["gatekeeper-project-excluded"]
        processes: ["*"]      
        
