apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pod-no
  labels:
    "gatekeeper": "true"
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "openshift/hello-openshift:latest"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
  namespace: gatekeeper-project
spec:
  selector:
    matchLabels:
      app: hello-openshift
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
        - name: hello-openshift
          image: openshift/hello-openshift
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "700m"
              memory: "800m"
