apiVersion: v1
kind: Pod
metadata:
  name: pod-yes
  labels:
    app: hello-openshift
  namespace: prueba
spec:
  containers:
    - name: hello-openshift
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080  
      resources:
        limits:
          cpu: "50m"
          memory: "200m"
