---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq
  namespace: gatekeeper-resourcequota
spec:
  hard:
    pods: '4'
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '2'
    limits.memory: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-rq-yes
  labels:
    app: hello-openshift
  namespace: gatekeeper-resourcequota
spec:
  containers:
    - name: hello-openshift
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: 50m
          cpu: 100m
        limits:
          memory: 60m
          cpu: 120m          
