apiVersion: v1
kind: Pod
metadata:
  name: pod-no
  labels:
    app: hello-openshift
spec:
  containers:
    - name: hello-openshift
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080  
      resources:
        requests:
          cpu: "700m"
          memory: "800m"
