apiVersion: v1
kind: Pod
metadata:
  name: pod-rq-no
  labels:
    app: hello-openshift
  namespace: gatekeeper-resourcequota
spec:
  containers:
    - name: hello-openshift
      image: openshift/hello-openshift
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: 50m
          cpu: 100m
        limits:
          memory: 60m
          cpu: 120m

