apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sMaxRequests
metadata:
  name: pod-max-requests
spec:
  enforcementAction: deny 
  match:
   #excludedNamespaces:
  #    - "gatekeeper-project-excluded"      
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpu: "100m"
    memory: "500m"
                
        
            
